In [1]:
import pandas as pd 
import numpy as np 
np.random.seed = 2021
from sklearn.datasets import load_iris
iris = load_iris()
print ('data contains:',iris.keys())
X, y, labels, feature_names  = iris.data, iris.target, iris.target_names, iris['feature_names']
df_iris= pd.DataFrame(X, columns= feature_names) 
df_iris['label'] =  y
features_dict = {k:v for k,v in  enumerate(labels)}
df_iris['label_names'] = df_iris.label.apply(lambda x: features_dict[x])
df_iris

data contains: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              

In [2]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df_iris, test_size=0.3)

In [3]:
X_train = train[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]
y_train = train['label']
X_test = test[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]

y_test = test['label']


print ('X_train.shape=', X_train.shape)
print ('y_train.shape=', y_train.shape)
print ('X_test.shape=', X_test.shape)
print ('y_test.shape=', y_test.shape)
print ('X_train[0]=')
X_train.iloc[0]

X_train.shape= (105, 4)
y_train.shape= (105,)
X_test.shape= (45, 4)
y_test.shape= (45,)
X_train[0]=


sepal length (cm)    6.7
sepal width (cm)     3.1
petal length (cm)    5.6
petal width (cm)     2.4
Name: 140, dtype: float64

In [4]:
flower_dict = dict(zip(df_iris['label'].unique(), df_iris['label_names'].unique()))
print (flower_dict)

{0: 'setosa', 1: 'versicolor', 2: 'virginica'}


In [5]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print ('X_train_scaled[0]=')
print (X_train_scaled)

X_train_scaled[0]=
[[ 1.05767567  0.06750304  1.09603882  1.64583038]
 [ 1.05767567 -0.1539913   0.76374601  0.73629254]
 [ 0.82485398  0.28899738  0.81912815  1.12609447]
 [-0.4556653   1.83945778 -1.06386444 -0.95284917]
 [-0.10643277 -0.1539913   0.32068893  0.08662265]
 [-0.92130868  1.17497475 -1.23001084 -1.21271712]
 [-0.80489784  1.61796344 -1.17462871 -1.08278314]
 [ 0.47562145 -0.37548565  0.37607107  0.21655663]
 [ 0.59203229 -0.59697999  0.81912815  0.47642458]
 [-1.38695205  0.06750304 -1.17462871 -1.21271712]
 [ 0.00997807 -0.81847433  0.15454253  0.08662265]
 [-0.33925446  0.95348041 -1.28539298 -1.21271712]
 [-0.68848699  0.73198607 -1.23001084 -1.21271712]
 [ 0.94126482 -0.37548565  0.54221747  0.21655663]
 [ 0.94126482 -0.1539913   0.4314532   0.34649061]
 [-0.92130868  0.28899738 -1.34077511 -1.21271712]
 [-1.61977374 -0.1539913  -1.28539298 -1.21271712]
 [-1.15413037  0.73198607 -0.95310017 -1.21271712]
 [ 1.17408651 -0.1539913   1.04065669  1.25602845]
 [ 2.2217841

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
clf= KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train_scaled, y_train)
print ('score train = {:.3f}'.format(clf.score(X_train_scaled,y_train)))
print ('score test = {:.3f}'.format(clf.score(X_test_scaled,y_test)))

score train = 0.971
score test = 0.978


In [9]:
clf= KNeighborsClassifier(n_neighbors=4)
clf.fit(X_train_scaled, y_train)
print ('score train = {:.3f}'.format(clf.score(X_train_scaled,y_train)))
print ('score test = {:.3f}'.format(clf.score(X_test_scaled,y_test)))

score train = 0.962
score test = 0.956


In [10]:
clf= KNeighborsClassifier(n_neighbors=10)
clf.fit(X_train_scaled, y_train)
print ('score train = {:.3f}'.format(clf.score(X_train_scaled,y_train)))
print ('score test = {:.3f}'.format(clf.score(X_test_scaled,y_test)))

score train = 0.952
score test = 0.978


In [11]:
clf= KNeighborsClassifier(n_neighbors=9)
clf.fit(X_train_scaled, y_train)
print ('score train = {:.3f}'.format(clf.score(X_train_scaled,y_train)))
print ('score test = {:.3f}'.format(clf.score(X_test_scaled,y_test)))

score train = 0.943
score test = 0.978


In [12]:
clf= KNeighborsClassifier(n_neighbors=11)
clf.fit(X_train_scaled, y_train)
print ('score train = {:.3f}'.format(clf.score(X_train_scaled,y_train)))
print ('score test = {:.3f}'.format(clf.score(X_test_scaled,y_test)))

score train = 0.943
score test = 0.956


In [13]:
clf= KNeighborsClassifier(n_neighbors=7)
clf.fit(X_train_scaled, y_train)
print ('score train = {:.3f}'.format(clf.score(X_train_scaled,y_train)))
print ('score test = {:.3f}'.format(clf.score(X_test_scaled,y_test)))

score train = 0.952
score test = 0.956


In [14]:
k_best = 10
score_best = 'score train = 0.952, score test = 0.978'
print ('The best k = {} , score = {}'.format(k_best,score_best ))

The best k = 10 , score = score train = 0.952, score test = 0.978
